version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: shopping_postgres
    restart: always
    environment:
      POSTGRES_USER: shopping_user
      POSTGRES_PASSWORD: shopping_pass
      POSTGRES_DB: shopping_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
